wip

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -23,7 +23,7 @@ jobs:
             - name: Checkout Repository
               uses: actions/checkout@v4
 
-            - name: Set up Docker Buildx
+            - name: Set up Docker with Buildx
               uses: docker/setup-buildx-action@v3
 
             - name: Build with Makefile
@@ -35,13 +35,13 @@ jobs:
                   DOCKER_INFRA_USER: ${{ secrets.DOCKER_INFRA_USER }}
                   DOCKER_INFRA_GROUP: ${{ secrets.DOCKER_INFRA_GROUP }}
 
-            - name: Find and Verify Build Artifact
+            - name: Find and Verify Built Artifact
               id: find_binary # Give the step an ID to reference its outputs
               run: |
-                  echo "Listing contents of the ./bin directory to verify the artifact:"
                   ls -la ./bin
                   # Find the executable file, excluding .gitkeep, and handle cases where no file or multiple files are found.
                   BINARY_PATH=$(find ./bin -type f -executable -not -name ".gitkeep")
+
                   if [ -z "$BINARY_PATH" ]; then
                     echo "::error::No executable binary found in ./bin directory."
                     exit 1
@@ -50,56 +50,43 @@ jobs:
                     echo "$BINARY_PATH"
                     exit 1
                   fi
-                  echo "Found binary: $BINARY_PATH"
-                  # Set the found path as an output for this step.
+
                   echo "path=$BINARY_PATH" >> $GITHUB_OUTPUT
 
             - name: Prepare Deployment Package
 #              if: github.event_name == 'push'
               run: tar -czvf deploy.tar.gz ${{ steps.find_binary.outputs.path }} Makefile
 
-            - name: Copy binary and Makefile to VPS
+            - name: Copy Binary and Makefile to VPS
               uses: appleboy/scp-action@v1.0.0
               with:
-                  host: ${{ secrets.HOSTINGER_HOST }}
-                  username: ${{ secrets.HOSTINGER_USERNAME }}
-                  key: ${{ secrets.HOSTINGER_SSH_KEY }}
-                  port: ${{ secrets.HOSTINGER_SSH_PORT }}
+                  host: ${{ secrets.VPS_HOST }}
+                  username: ${{ secrets.VPS_USERNAME }}
+                  key: ${{ secrets.VPS_SSH_KEY }}
+                  port: ${{ secrets.VPS_SSH_PORT }}
                   source: "deploy.tar.gz"
-                  target: "${{ secrets.HOSTINGER_TARGET_DIR }}/"
+                  target: "${{ secrets.VPS_TARGET_DIR }}/"
 
-            - name: SSH and Restart Application
+            - name: SSH and Restart Services
               uses: appleboy/ssh-action@v1.0.0
               with:
-                  host: ${{ secrets.HOSTINGER_HOST }}
-                  username: ${{ secrets.HOSTINGER_USERNAME }}
-                  key: ${{ secrets.HOSTINGER_SSH_KEY }}
-                  port: ${{ secrets.HOSTINGER_SSH_PORT }}
+                  host: ${{ secrets.VPS_HOST }}
+                  username: ${{ secrets.VPS_USERNAME }}
+                  key: ${{ secrets.VPS_SSH_KEY }}
+                  port: ${{ secrets.VPS_SSH_PORT }}
                   script: |
-                        set -e # Exit immediately if a command fails.
-                        echo "--- Changing to directory: ${{ secrets.HOSTINGER_TARGET_DIR }}"
-                        cd ${{ secrets.HOSTINGER_TARGET_DIR }}
+                    set -e # Exit immediately if a command fails.
+                    cd ${{ secrets.VPS_TARGET_DIR }}
 
-                        echo "--- Unpacking deployment package ---"
-                        tar -xzvf deploy.tar.gz
-                        rm deploy.tar.gz
+                    tar -xzvf deploy.tar.gz
+                    rm deploy.tar.gz
 
-                        # The binary is now in a 'bin' subdirectory created by tar.
-                        SOURCE_FILENAME_ON_SERVER="./bin/$(basename "${{ steps.find_binary.outputs.path }}")"
-                        FINAL_BINARY_NAME="${{ secrets.DOCKER_BINARY_NAME }}"
+                    SOURCE_FILENAME_ON_SERVER="./bin/$(basename "${{ steps.find_binary.outputs.path }}")"
+                    FINAL_BINARY_NAME="${{ secrets.DOCKER_BINARY_NAME }}"
 
-                        echo "--- Moving '$SOURCE_FILENAME_ON_SERVER' to './$FINAL_BINARY_NAME'"
-                        mv -f "$SOURCE_FILENAME_ON_SERVER" "./$FINAL_BINARY_NAME"
+                    mv -f "$SOURCE_FILENAME_ON_SERVER" "./$FINAL_BINARY_NAME"
+                    rm -rf ./bin
+                    chmod +x "$FINAL_BINARY_NAME"
 
-                        echo "--- Cleaning up empty 'bin' directory"
-                        rm -rf ./bin
-
-                        echo "--- Making '$FINAL_BINARY_NAME' executable"
-                        chmod +x "$FINAL_BINARY_NAME"
-
-                        echo "--- Restarting service via Makefile"
-                        make sup-api-restart API_SUPERVISOR_NAME=${{ secrets.API_SUPERVISOR }}
-
-                        echo "--- Checking service status via Makefile"
-                        make sup-api-status API_SUPERVISOR_NAME=${{ secrets.API_SUPERVISOR }}
-
+                    make sup-api-restart API_SUPERVISOR_NAME=${{ secrets.API_SUPERVISOR }}
+                    make sup-api-status API_SUPERVISOR_NAME=${{ secrets.API_SUPERVISOR }}
